### ISSUE TITLE
reference_matcher line 78

### ISSUE THREAD

**Issue by griffinjbell** [xiaoyu518/genofunc#1]
Received on two machines (Windows running WSL) on two different datasets.

**Error:**

reference_matcher(
  File ".../python3.9/site-packages/genofunc/reference_matcher.py", line 78, in reference_matcher
    for hit in reference_list.map(record.seq):
  File "python/mappy.pyx", line 185, in map
AttributeError: 'Seq' object has no attribute 'encode'

**Solution?**
Replacing record.seq with str(record.seq) on line 78 of reference_matcher. I think this solved it for me.

**Comment by xiaoyu518** [comment]
Thanks for feedback. The problem has been addressed with the solution given. As the software was mainly tested using macOS, any feedback from other systems are greatly appreciated.
